
#define WORKED_OK 0
#define INVALID_HEX_DIGIT_IN_VALUE 1

#define INCOMING_HEX_VALUE_TOO_BIG_FOR_BUFFER 2
#define INCOMING_HEX_VALUE_IS_THE_WRONG_LENGTH 3


#define JSON_COMMAND_OK 0
#define JSON_MESSAGE_COULD_NOT_BE_PARSED -1
#define JSON_MESSAGE_MISSING_COMMAND_NAME -2
#define JSON_MESSAGE_COMMAND_NAME_INVALID -3
#define JSON_MESSAGE_INVALID_DATA_TYPE -4
#define JSON_MESSAGE_INVALID_DATA_VALUE -5
#define INVALID_OR_MISSING_TARGET_IN_RECEIVED_COMMAND -6
#define COMMAND_FOR_DIFFERENT_TARGET -7


